const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_KEY environment variables");
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

/**
 * API contract:
 * - GET /api/sync
 *    Headers: Authorization: Bearer <SYNC_TOKEN>
 *    Response: { payload: "<base64-string>", updated_at: "<iso>" } or 404
 *
 * - POST /api/sync
 *    Headers: Authorization: Bearer <SYNC_TOKEN>
 *    Body: { payload: "<base64-string>" }
 *    Upserts row (token, payload, updated_at)
 *
 * Notes:
 * - The server stores whatever payload the client sends (recommended: encrypted).
 * - The SYNC_TOKEN is a secret value generated by client and must be kept safe.
 */

module.exports = async (req, res) => {
  try {
    const auth = req.headers.authorization || '';
    const token = (auth.startsWith('Bearer ') ? auth.slice(7).trim() : null) || req.query.token;

    if (!token) {
      return res.status(401).json({ error: 'Missing Authorization Bearer token' });
    }

    if (req.method === 'GET') {
      const { data, error } = await supabase
        .from('histories')
        .select('payload, updated_at')
        .eq('token', token)
        .limit(1)
        .single();

      if (error && error.code === 'PGRST116') {
        // no rows
        return res.status(404).json({ error: 'No synced data' });
      }

      if (error) {
        console.error('Supabase select error:', error);
        return res.status(500).json({ error: 'Error reading sync data' });
      }

      return res.json({ payload: data.payload, updated_at: data.updated_at });
    }

    if (req.method === 'POST') {
      const body = req.body || {};
      const payload = body.payload;
      if (!payload) {
        return res.status(400).json({ error: 'Missing payload in request body' });
      }

      const now = new Date().toISOString();
      // Upsert by token
      const { data, error } = await supabase
        .from('histories')
        .upsert({ token, payload, updated_at: now }, { onConflict: ['token'] });

      if (error) {
        console.error('Supabase upsert error:', error);
        return res.status(500).json({ error: 'Error saving sync data' });
      }

      return res.json({ ok: true, updated_at: now });
    }

    res.setHeader('Allow', 'GET, POST');
    return res.status(405).end();
  } catch (err) {
    console.error('Sync API error', err);
    return res.status(500).json({ error: 'Server error', details: String(err) });
  }
};
